name: work_flow_1
on: workflow_dispatch
jobs:
  android-lint:
    runs-on: ubuntu-latest
    steps:
      - name: check out the code
        uses: actions/checkout@v3
      - name: set JDK 17
        uses: actions/setup-java@v3
        with: 
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Run Lint
        run: ./gradlew lint
        continue-on-error: false
  test:
    runs-on: ubuntu-latest
    steps: 
      - name: set JDK 17
        uses: actions/checkout@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v3
      - name: set JDK 17
        uses: actions/checkout@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Deploy Code
        run: echo "{{ toJSON(github) }}"
